@echo off
echo Restarting all services...

echo Stopping existing processes...
taskkill /f /im node.exe 2>nul
taskkill /f /im expo.exe 2>nul

echo Waiting 3 seconds...
timeout /t 3 /nobreak >nul

echo Starting Backend...
start "Backend" cmd /k "cd backend && node src/server.js"

echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul

echo Starting Webadmin...
start "Webadmin" cmd /k "cd webadmin && npm run dev"

echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul

echo Starting Mobile App...
start "Mobile App" cmd /k "cd frontend/mobile && npx expo start --port 8083 --clear"

echo Waiting 2 seconds...
timeout /t 2 /nobreak >nul

echo Starting Employee App...
start "Employee App" cmd /k "cd frontend/mobile-employee && npx expo start --port 8082 --clear"

echo All services started!
pause
